### ISSUE TITLE
Argument type mismatch

### ISSUE THREAD

**Issue by jsseidel** [dfrommi/groovy-pandoc#4]
Hi there --

I tried to upgrade to the 0.8 version, but I can't run any of the examples. Here's what happens when I run Behead.groovy, for example:

```
CLASSPATH=~/groovy-pandoc/build/libs/GroovyPandoc-0.8.jar; pandoc -f markdown -t markdown --filter ./Behead.groovy example.md 
Caught: java.lang.IllegalArgumentException: argument type mismatch
java.lang.IllegalArgumentException: argument type mismatch
        at com.github.dfrommi.pandoc.convert.PandocConverter.methodMissing(PandocConverter.groovy:140)
        at com.github.dfrommi.pandoc.convert.PandocConverter.methodMissing(PandocConverter.groovy:141)
        at com.github.dfrommi.pandoc.PandocFilter.toJSONFilter(PandocFilter.groovy:82)
        at com.github.dfrommi.pandoc.PandocFilter$toJSONFilter$1.callCurrent(Unknown Source)
        at com.github.dfrommi.pandoc.PandocFilter.toJSONFilter(PandocFilter.groovy:59)
        at com.github.dfrommi.pandoc.PandocFilter$toJSONFilter$0.callCurrent(Unknown Source)
        at com.github.dfrommi.pandoc.PandocFilter.toJSONFilter(PandocFilter.groovy:29)
        at com.github.dfrommi.pandoc.PandocFilter$toJSONFilter.call(Unknown Source)
        at com.github.dfrommi.pandoc.Pandoc.toJSONFilter(Pandoc.groovy:17)
        at com.github.dfrommi.pandoc.Pandoc$toJSONFilter.callStatic(Unknown Source)
        at Behead.run(Behead.groovy:8)
pandoc: Error running filter ./Behead.groovy
Filter returned error status 1
```
It runs fine with an older version.

Any ideas?

**Comment by jsseidel** [comment]
The issue was a mismatch in versions. GroovyPandoc-0.8.jar works with pandoc 1.19 and GroovyPandoc-0.7.jar (or less) will only work with older versions of pandoc. Specifically, pandoc got rid of the unMeta object in the AST JSON, so older versions of groovy-pandoc throw up because they can't find it. Similarly, newer groovy-pandoc won't work with older pandoc for the same reason reversed (as seen above).
